# Generated by Django 4.1.4 on 2022-12-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoders3', '0002_students_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='student'),
        ),
    ]
