# Generated by Django 4.1.4 on 2022-12-31 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoders3', '0003_alter_students_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='teacher'),
        ),
    ]
